# Generated by Django 4.1.13 on 2025-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_userprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_transcription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transcription_count',
            field=models.IntegerField(default=0),
        ),
    ]
